import type { NextPage } from 'next'
import Head from 'next/head'
import BooksList from '../components/booksList'
import products from '../util/database'
import NavContainer from '../components/navbar/container'

const Home: NextPage = () => {
  const {books} = products
  return (
    <div className='text-center text-blue-600 text-lg'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <NavContainer />
      <BooksList books={books}/>
    </div>
  )
}

export default Home
